import type { DashboardSummary } from "./dashboard";
import type { Item } from "./items";

export const DEMO_ITEMS: Item[] = [
  {
    id: "demo-item-1",
    item_code: "DEMO-0001",
    name: "Demo Peacock Kundan Bridal Set",
    category: "Bridal Set",
    item_type: "set",
    components: ["Necklace", "Earrings", "Maang Tikka", "Bangles"],
    tracking_type: "unique",
    quantity_on_hand: null,
    status: "available",
    rental_price: 8500,
    sale_price: 42500,
    security_deposit_default: 5000,
    current_location: "Display Case 1",
    photos: [],
    notes: "Sample bridal set for local demo mode. Replace with live inventory data later.",
    is_active: true,
    created_at: "2026-08-13T00:00:00.000Z",
    updated_at: "2026-08-13T00:00:00.000Z",
  },
  {
    id: "demo-item-2",
    item_code: "DEMO-0002",
    name: "Demo Temple Choker",
    category: "Temple",
    item_type: "single",
    components: null,
    tracking_type: "quantity",
    quantity_on_hand: 4,
    status: "available",
    rental_price: 2400,
    sale_price: 9800,
    security_deposit_default: 1500,
    current_location: "Shelf B2",
    photos: [],
    notes: "Quantity-stock sample so list and stock columns stay meaningful in demo mode.",
    is_active: true,
    created_at: "2026-08-13T00:00:00.000Z",
    updated_at: "2026-08-13T00:00:00.000Z",
  },
];

export const DEMO_DASHBOARD_SUMMARY: DashboardSummary = {
  today: "2026-08-13",
  due_today: [
    {
      id: "demo-due-1",
      booking_id: "demo-booking-1",
      item_id: "demo-item-1",
      quantity_booked: 1,
      type: "rental",
      pickup_date: "2026-08-12",
      return_date: "2026-08-13",
      actual_return_date: null,
      status: "out",
      price_charged: 8500,
      bookings: { booking_code: "RNT-DEMO1", customer_id: "demo-customer-1" },
      items: {
        id: "demo-item-1",
        item_code: "DEMO-0001",
        name: "Demo Peacock Kundan Bridal Set",
        category: "Bridal Set",
        item_type: "set",
        tracking_type: "unique",
      },
      customers: { id: "demo-customer-1", name: "Ananya Sharma", phone: "9876543210" },
    },
  ],
  overdue: [
    {
      id: "demo-overdue-1",
      booking_id: "demo-booking-2",
      item_id: "demo-item-2",
      quantity_booked: 2,
      type: "rental",
      pickup_date: "2026-08-05",
      return_date: "2026-08-10",
      status: "out",
      booking_code: "RNT-DEMO2",
      customer_id: "demo-customer-2",
      items: { item_code: "DEMO-0002", name: "Demo Temple Choker" },
      customers: { name: "Priya Mehta", phone: "9988776655" },
      balance_due: 1800,
      days_until_return: -3,
      next_booking_code: "RNT-DEMO3",
      next_customer_name: "Meera Iyer",
      next_pickup_date: "2026-08-14",
      next_customer_waiting: true,
    },
  ],
  outstanding_balance: 1800,
  outstanding_balance_count: 1,
  stats: {
    total_active_items: 2,
    items_out: 2,
    total_customers: 3,
    bookings_this_week: 4,
  },
};